### ISSUE TITLE
When grepprg uses the native grep command, it is expecting you to pass a dir or feed data from stdin

### ISSUE THREAD

**Issue by chrisjohnson** [teoljungberg/vim-grep#4]
By default, running the following command will hang, waiting for input on stdin:

`grep -rnH foo`

It expects you to either pass in the data to search via stdin, or to pass it a directory as the last argument.

My question is, does this plugin actually work for anybody who doesn't have ag installed and isn't grepping in a git repo? Is this just an issue on my end?

If the answer to that is no, then my proposal would be a fix in the Grep function that will append `getcwd()` to the `a:args` variable if `grepprg` starts with "grep". I can implement that if you want. Let me know what you think

**Comment by teoljungberg** [comment]
@chrisjohnson I do not actively use this plugin anymore as I've moved over to use `rg(1)` for everything. 

But I think your suggestion makes sense. PRs are welcome!

**Comment by chrisjohnson** [comment]
Curious, never heard of rg. After trying it out, I like it.

I'm gonna add first-class support for it in this plugin if you don't mind -- if rg is present, it should be used above all over tools. I'll also implement the fix in native grep.

Is there another plugin you prefer to use for rg or do you just set grepprg manually now? The main reason I like this plugin is for Dispatch support and (with my change) support for auto-selecting the search tool.

**Comment by teoljungberg** [comment]
@chrisjohnson I currently set it as my `grepprg` in my dotfiles - https://github.com/teoljungberg/dotfiles/blob/master/vim/plugin/grep.vim#L5-L10. And with that, I haven't felt the need to do the auto selection of the search tool.
